### ISSUE TITLE
Register teams slack command

### ISSUE THREAD

**Issue by TheSabby** [chingu-x/chingu-wizard#45]
**Register**
(Slack - ADMIN) user enters /autobot register teams

**Comment by the-vampiire** [comment]
uses chinguAPI mutation `autobotCreateCohortTeam`

**Comment by the-vampiire** [comment]
create [temporary] admin command `/admin autobotCreateTeams`
calls chinguAPI mutation `autobotCreateCohortTeam`
passes `slack_team_id, title [slack_channel_name], slack_channel_id`
